name: subsetter
on:
  push:
    branches:
      - main
jobs:
  python-versions:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install package deps
      run: python -m pip install -e .
    - name: Install dev deps
      run: python -m pip install -r requirements-dev.txt
    - name: Lint
      run: make lint
    - name: Test
      run: make test
